import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import mysql from 'mysql2/promise'
import pg from 'pg'

const { Pool } = pg
const app = express()
const port = process.env.PORT || 3001

app.use(cors())
app.use(express.json({ limit: '1mb' }))

function parseConnection(connectionString) {
  const url = new URL(connectionString)
  const protocol = url.protocol.replace(':', '').toLowerCase()
  if (['mysql', 'mysql2'].includes(protocol)) return { kind: 'mysql', url }
  if (['postgres', 'postgresql'].includes(protocol)) return { kind: 'postgres', url }
  throw new Error('Protocole non pris en charge. Utilisez mysql:// ou postgresql://.')
}

function quoteIdentifier(name, kind) {
  if (kind === 'mysql') return `\`${name.replaceAll('`', '``')}\``
  return `"${name.replaceAll('"', '""')}"`
}

function getMysqlConfig(url) {
  return { host: url.hostname, port: Number(url.port || 3306), user: decodeURIComponent(url.username), password: decodeURIComponent(url.password), database: decodeURIComponent(url.pathname.slice(1)), connectTimeout: 8000 }
}

function getPostgresConfig(url) {
  return { connectionString: url.toString(), connectionTimeoutMillis: 8000, ssl: url.searchParams.get('sslmode') === 'require' ? { rejectUnauthorized: false } : false }
}

async function withDatabase(connectionString, action) {
  const parsed = parseConnection(connectionString)
  if (parsed.kind === 'mysql') {
    const connection = await mysql.createConnection(getMysqlConfig(parsed.url))
    try { return await action({ kind: parsed.kind, client: connection }) } finally { await connection.end() }
  }
  const pool = new Pool(getPostgresConfig(parsed.url))
  const client = await pool.connect()
  try { return await action({ kind: parsed.kind, client }) } finally { client.release(); await pool.end() }
}

async function listTables(database) {
  if (database.kind === 'mysql') {
    const [rows] = await database.client.query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'")
    return rows.map((row) => Object.values(row)[0])
  }
  const result = await database.client.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name")
  return result.rows.map((row) => row.table_name)
}

async function getMysqlCreateStatement(client, table) {
  const [rows] = await client.query(`SHOW CREATE TABLE ${quoteIdentifier(table, 'mysql')}`)
  return Object.values(rows[0])[1]
}

async function getPostgresCreateStatement(client, table) {
  const result = await client.query("SELECT column_name, data_type, udt_name, is_nullable, column_default, character_maximum_length, numeric_precision, numeric_scale FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 ORDER BY ordinal_position", [table])
  const columns = result.rows.map((column) => {
    let type = column.data_type
    if (column.data_type === 'USER-DEFINED') type = quoteIdentifier(column.udt_name, 'postgres')
    if (column.character_maximum_length) type += `(${column.character_maximum_length})`
    if (column.numeric_precision && ['numeric', 'decimal'].includes(column.data_type)) type += `(${column.numeric_precision},${column.numeric_scale || 0})`
    const nullable = column.is_nullable === 'NO' ? ' NOT NULL' : ''
    const isSerialDefault = column.column_default?.startsWith('nextval(')
    const defaultValue = isSerialDefault ? ' GENERATED BY DEFAULT AS IDENTITY' : column.column_default ? ` DEFAULT ${column.column_default}` : ''
    return `${quoteIdentifier(column.column_name, 'postgres')} ${type}${defaultValue}${nullable}`
  })
  return `CREATE TABLE ${quoteIdentifier(table, 'postgres')} (${columns.join(', ')})`
}

function convertColumnType(type, sourceKind, targetKind) {
  if (sourceKind === targetKind) return type
  const normalized = type.toLowerCase()
  if (sourceKind === 'mysql' && targetKind === 'postgres') {
    if (normalized === 'tinyint(1)') return 'boolean'
    if (normalized.startsWith('tinyint') || normalized.startsWith('smallint')) return 'smallint'
    if (normalized.startsWith('mediumint') || normalized.startsWith('int')) return 'integer'
    if (normalized.startsWith('datetime')) return 'timestamp'
    if (normalized.startsWith('longtext') || normalized.startsWith('mediumtext')) return 'text'
    if (normalized.startsWith('blob')) return 'bytea'
  }
  if (sourceKind === 'postgres' && targetKind === 'mysql') {
    if (normalized === 'boolean') return 'TINYINT(1)'
    if (normalized === 'integer') return 'INT'
    if (normalized.startsWith('timestamp')) return 'DATETIME'
    if (normalized === 'jsonb') return 'JSON'
    if (normalized === 'bytea') return 'BLOB'
  }
  return type
}

async function getCrossDatabaseCreateStatement(sourceDb, targetKind, table) {
  let columns
  if (sourceDb.kind === 'mysql') {
    const [rows] = await sourceDb.client.query(`SHOW COLUMNS FROM ${quoteIdentifier(table, 'mysql')}`)
    columns = rows.map((column) => ({ name: column.Field, type: column.Type, nullable: column.Null === 'YES' }))
  } else {
    const result = await sourceDb.client.query("SELECT column_name, data_type, udt_name, is_nullable, character_maximum_length, numeric_precision, numeric_scale FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 ORDER BY ordinal_position", [table])
    columns = result.rows.map((column) => {
      let type = column.data_type === 'USER-DEFINED' ? column.udt_name : column.data_type
      if (column.character_maximum_length) type += `(${column.character_maximum_length})`
      if (column.numeric_precision && ['numeric', 'decimal'].includes(column.data_type)) type += `(${column.numeric_precision},${column.numeric_scale || 0})`
      return { name: column.column_name, type, nullable: column.is_nullable === 'YES' }
    })
  }
  const definitions = columns.map((column) => `${quoteIdentifier(column.name, targetKind)} ${convertColumnType(column.type, sourceDb.kind, targetKind)}${column.nullable ? '' : ' NOT NULL'}`)
  return `CREATE TABLE ${quoteIdentifier(table, targetKind)} (${definitions.join(', ')})`
}

async function getTableRows(client, kind, table) {
  const result = await client.query(`SELECT * FROM ${quoteIdentifier(table, kind)}`)
  return kind === 'mysql' ? result[0] : result.rows
}

app.post('/api/test', async (request, response) => {
  try {
    const { connectionString } = request.body
    if (!connectionString) throw new Error('Chaîne de connexion manquante.')
    const result = await withDatabase(connectionString, async (database) => ({ kind: database.kind, tables: await listTables(database) }))
    response.json({ ok: true, ...result })
  } catch (error) { response.status(400).json({ ok: false, error: error.message }) }
})

app.get('/health', (request, response) => response.json({ ok: true }))

app.post('/api/transfer', async (request, response) => {
  const { source, target, tables, replaceExisting = false } = request.body
  if (!source || !target || !Array.isArray(tables) || tables.length === 0) return response.status(400).json({ ok: false, error: 'Source, cible et tables sont obligatoires.' })
  try {
    const details = await withDatabase(source, async (sourceDb) => withDatabase(target, async (targetDb) => {
      const availableTables = await listTables(sourceDb)
      const selectedTables = tables.filter((table) => availableTables.includes(table))
      const copied = []
      for (const table of selectedTables) {
        const sourceCreate = sourceDb.kind === 'mysql' ? await getMysqlCreateStatement(sourceDb.client, table) : await getPostgresCreateStatement(sourceDb.client, table)
        const rows = await getTableRows(sourceDb.client, sourceDb.kind, table)
        const targetName = quoteIdentifier(table, targetDb.kind)
        if (replaceExisting) await targetDb.client.query(`DROP TABLE IF EXISTS ${targetName}`)
        const targetCreate = sourceDb.kind === targetDb.kind
          ? sourceCreate
          : await getCrossDatabaseCreateStatement(sourceDb, targetDb.kind, table)
        await targetDb.client.query(targetCreate)
        if (rows.length > 0) {
          const columns = Object.keys(rows[0])
          const columnSql = columns.map((column) => quoteIdentifier(column, targetDb.kind)).join(', ')
          const placeholders = rows.map((row, rowIndex) => targetDb.kind === 'mysql' ? `(${columns.map(() => '?').join(', ')})` : `(${columns.map((_, index) => `$${rowIndex * columns.length + index + 1}`).join(', ')})`)
          const values = rows.flatMap((row) => columns.map((column) => row[column]))
          await targetDb.client.query(`INSERT INTO ${targetName} (${columnSql}) VALUES ${placeholders.join(', ')}`, values)
        }
        copied.push({ table, rows: rows.length })
      }
      return copied
    }))
    response.json({ ok: true, details })
  } catch (error) { response.status(400).json({ ok: false, error: error.message }) }
})

app.listen(port, () => console.log(`Transfer BDD API disponible sur http://localhost:${port}`))